// Code generated by protoc-gen-go.
// source: services/node/v1/node.proto
// DO NOT EDIT!

/*
Package node is a generated protocol buffer package.

It is generated from these files:
	services/node/v1/node.proto

It has these top-level messages:
	InfoRequest
	InfoResponse
	Info
	Label
	Filesystem
*/
package node

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InfoRequest struct {
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InfoResponse struct {
	Info *Info `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InfoResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type Info struct {
	// Labels for the node
	Labels []*Label `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
	// Node hostname
	Hostname string `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	// IP addresses
	Addresses []string `protobuf:"bytes,3,rep,name=addresses" json:"addresses,omitempty"`
	// Port
	GrpcPort int64 `protobuf:"varint,4,opt,name=grpcPort" json:"grpcPort,omitempty"`
	// The machine id is an ID identifying a specific Linux/Unix installation.
	// It does not change if hardware is replaced.
	MachineID string `protobuf:"bytes,5,opt,name=machineID" json:"machineID,omitempty"`
	// The system uuid is the main board product UUID,
	// as set by the board manufacturer and encoded in the BIOS DMI information
	SystemUUID string `protobuf:"bytes,6,opt,name=systemUUID" json:"systemUUID,omitempty"`
	// A random ID that is regenerated on each boot
	BootID string `protobuf:"bytes,7,opt,name=bootID" json:"bootID,omitempty"`
	// Node operating system. One of 386, amd64, arm, s390x, and so on.
	Arch string `protobuf:"bytes,8,opt,name=arch" json:"arch,omitempty"`
	// node operating system. One of darwin, freebsd, linux, windows, and so on
	Os string `protobuf:"bytes,9,opt,name=os" json:"os,omitempty"`
	// Server version
	Version string `protobuf:"bytes,10,opt,name=version" json:"version,omitempty"`
	// Filesystem infos
	Filesystems []*Filesystem `protobuf:"bytes,11,rep,name=filesystems" json:"filesystems,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Info) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Info) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Info) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Info) GetGrpcPort() int64 {
	if m != nil {
		return m.GrpcPort
	}
	return 0
}

func (m *Info) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *Info) GetSystemUUID() string {
	if m != nil {
		return m.SystemUUID
	}
	return ""
}

func (m *Info) GetBootID() string {
	if m != nil {
		return m.BootID
	}
	return ""
}

func (m *Info) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Info) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Info) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Info) GetFilesystems() []*Filesystem {
	if m != nil {
		return m.Filesystems
	}
	return nil
}

type Label struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Label) Reset()                    { *m = Label{} }
func (m *Label) String() string            { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()               {}
func (*Label) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Label) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Filesystem struct {
	// E.g /dev/vda1, tmpfs, cgroup, etc.
	Filesystem string `protobuf:"bytes,1,opt,name=filesystem" json:"filesystem,omitempty"`
	// E.g. ext4, tmpfs, cgroup, etc.
	TypeName string `protobuf:"bytes,2,opt,name=typeName" json:"typeName,omitempty"`
	// Path to the mounted dir
	MountDir string `protobuf:"bytes,3,opt,name=mountDir" json:"mountDir,omitempty"`
	// Total data blocks
	Total uint64 `protobuf:"varint,4,opt,name=total" json:"total,omitempty"`
	// Free blocks
	Free uint64 `protobuf:"varint,5,opt,name=free" json:"free,omitempty"`
	// Free blocks available to unprivileged user
	Available uint64 `protobuf:"varint,6,opt,name=available" json:"available,omitempty"`
}

func (m *Filesystem) Reset()                    { *m = Filesystem{} }
func (m *Filesystem) String() string            { return proto.CompactTextString(m) }
func (*Filesystem) ProtoMessage()               {}
func (*Filesystem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Filesystem) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

func (m *Filesystem) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Filesystem) GetMountDir() string {
	if m != nil {
		return m.MountDir
	}
	return ""
}

func (m *Filesystem) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Filesystem) GetFree() uint64 {
	if m != nil {
		return m.Free
	}
	return 0
}

func (m *Filesystem) GetAvailable() uint64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func init() {
	proto.RegisterType((*InfoRequest)(nil), "eliot.services.containers.v1.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "eliot.services.containers.v1.InfoResponse")
	proto.RegisterType((*Info)(nil), "eliot.services.containers.v1.Info")
	proto.RegisterType((*Label)(nil), "eliot.services.containers.v1.Label")
	proto.RegisterType((*Filesystem)(nil), "eliot.services.containers.v1.Filesystem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/eliot.services.containers.v1.Node/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eliot.services.containers.v1.Node/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eliot.services.containers.v1.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Node_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/node/v1/node.proto",
}

func init() { proto.RegisterFile("services/node/v1/node.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x8a, 0xdb, 0x30,
	0x10, 0xc5, 0xb1, 0x93, 0xdd, 0x4c, 0xda, 0x52, 0x44, 0x29, 0x62, 0xbb, 0x94, 0xe0, 0x5e, 0xdc,
	0x1e, 0x6c, 0x36, 0x85, 0x96, 0xb2, 0xb7, 0x12, 0x16, 0x52, 0xca, 0x52, 0x04, 0x7b, 0x29, 0xf4,
	0xa0, 0x38, 0x93, 0x44, 0xac, 0x23, 0xb9, 0x92, 0x62, 0xc8, 0x3f, 0xf5, 0x07, 0x7b, 0x2b, 0x1a,
	0x27, 0x71, 0xe8, 0x21, 0xec, 0x49, 0x7a, 0x6f, 0xe6, 0x8d, 0xe0, 0xbd, 0x11, 0xbc, 0x71, 0x68,
	0x1b, 0x55, 0xa2, 0x2b, 0xb4, 0x59, 0x60, 0xd1, 0xdc, 0xd0, 0x99, 0xd7, 0xd6, 0x78, 0xc3, 0xae,
	0xb1, 0x52, 0xc6, 0xe7, 0x87, 0x96, 0xbc, 0x34, 0xda, 0x4b, 0xa5, 0xd1, 0xba, 0xbc, 0xb9, 0x49,
	0x9f, 0xc3, 0x68, 0xa6, 0x97, 0x46, 0xe0, 0xef, 0x2d, 0x3a, 0x9f, 0xde, 0xc1, 0xb3, 0x16, 0xba,
	0xda, 0x68, 0x87, 0xec, 0x13, 0x24, 0x4a, 0x2f, 0x0d, 0x8f, 0xc6, 0x51, 0x36, 0x9a, 0xa4, 0xf9,
	0xb9, 0x59, 0x39, 0x29, 0xa9, 0x3f, 0xfd, 0xdb, 0x83, 0x24, 0x40, 0x76, 0x0b, 0x83, 0x4a, 0xce,
	0xb1, 0x72, 0x3c, 0x1a, 0xc7, 0xd9, 0x68, 0xf2, 0xee, 0xfc, 0x88, 0xef, 0xa1, 0x57, 0xec, 0x25,
	0xec, 0x0a, 0x2e, 0xd7, 0xc6, 0x79, 0x2d, 0x37, 0xc8, 0x7b, 0xe3, 0x28, 0x1b, 0x8a, 0x23, 0x66,
	0xd7, 0x30, 0x94, 0x8b, 0x85, 0x45, 0xe7, 0xd0, 0xf1, 0x78, 0x1c, 0x67, 0x43, 0xd1, 0x11, 0x41,
	0xb9, 0xb2, 0x75, 0xf9, 0xc3, 0x58, 0xcf, 0x93, 0x71, 0x94, 0xc5, 0xe2, 0x88, 0x83, 0x72, 0x23,
	0xcb, 0xb5, 0xd2, 0x38, 0x9b, 0xf2, 0x3e, 0x8d, 0xed, 0x08, 0xf6, 0x16, 0xc0, 0xed, 0x9c, 0xc7,
	0xcd, 0xc3, 0xc3, 0x6c, 0xca, 0x07, 0x54, 0x3e, 0x61, 0xd8, 0x6b, 0x18, 0xcc, 0x8d, 0xf1, 0xb3,
	0x29, 0xbf, 0xa0, 0xda, 0x1e, 0x31, 0x06, 0x89, 0xb4, 0xe5, 0x9a, 0x5f, 0x12, 0x4b, 0x77, 0xf6,
	0x02, 0x7a, 0xc6, 0xf1, 0x21, 0x31, 0x3d, 0xe3, 0x18, 0x87, 0x8b, 0x06, 0xad, 0x53, 0x46, 0x73,
	0x20, 0xf2, 0x00, 0xd9, 0x37, 0x18, 0x2d, 0x55, 0x85, 0xed, 0x3b, 0x8e, 0x8f, 0xc8, 0xab, 0xec,
	0xbc, 0x57, 0x77, 0x47, 0x81, 0x38, 0x15, 0xa7, 0x05, 0xf4, 0xc9, 0x46, 0xf6, 0x12, 0xe2, 0x47,
	0xdc, 0x51, 0x76, 0x43, 0x11, 0xae, 0xec, 0x15, 0xf4, 0x1b, 0x59, 0x6d, 0x0f, 0x6e, 0xb6, 0x20,
	0xfd, 0x13, 0x01, 0x74, 0xc3, 0x82, 0x03, 0xdd, 0xb8, 0xbd, 0xfa, 0x84, 0x09, 0xde, 0xfa, 0x5d,
	0x8d, 0xf7, 0x27, 0xa9, 0x1c, 0x70, 0xa8, 0x6d, 0xcc, 0x56, 0xfb, 0xa9, 0xb2, 0x3c, 0x6e, 0x6b,
	0x07, 0x1c, 0x1e, 0xf7, 0xc6, 0xcb, 0x8a, 0x02, 0x49, 0x44, 0x0b, 0x82, 0x6f, 0x4b, 0x8b, 0x48,
	0x41, 0x24, 0x82, 0xee, 0x94, 0x6d, 0x23, 0x55, 0x25, 0xe7, 0x15, 0x52, 0x04, 0x89, 0xe8, 0x88,
	0x09, 0x42, 0x72, 0x6f, 0x16, 0xc8, 0x7e, 0xed, 0x57, 0xec, 0xfd, 0x13, 0xb6, 0xb2, 0x5d, 0xef,
	0xab, 0x0f, 0x4f, 0x69, 0x6d, 0x57, 0xff, 0xeb, 0x97, 0x9f, 0x9f, 0x57, 0xca, 0xaf, 0xb7, 0xf3,
	0xbc, 0x34, 0x9b, 0x02, 0xad, 0x36, 0x52, 0xd6, 0xb2, 0xa0, 0x01, 0x45, 0xfd, 0xb8, 0x2a, 0x64,
	0xad, 0x8a, 0xff, 0x3f, 0xde, 0x6d, 0x38, 0xe7, 0x03, 0xfa, 0x79, 0x1f, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xc9, 0xdd, 0x96, 0x50, 0x98, 0x03, 0x00, 0x00,
}
