// Code generated by protoc-gen-go.
// source: services/device/v1/device.proto
// DO NOT EDIT!

/*
Package device is a generated protocol buffer package.

It is generated from these files:
	services/device/v1/device.proto

It has these top-level messages:
	InfoRequest
	InfoResponse
	Info
	Label
*/
package device

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InfoRequest struct {
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InfoResponse struct {
	Info *Info `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InfoResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type Info struct {
	// Labels for the device
	Labels []*Label `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
	// Device hostname
	Hostname string `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	// IP addresses
	Addresses []string `protobuf:"bytes,3,rep,name=addresses" json:"addresses,omitempty"`
	// Port
	GrpcPort int64 `protobuf:"varint,4,opt,name=grpcPort" json:"grpcPort,omitempty"`
	// The machine id is an ID identifying a specific Linux/Unix installation.
	// It does not change if hardware is replaced.
	MachineID string `protobuf:"bytes,5,opt,name=machineID" json:"machineID,omitempty"`
	// The system uuid is the main board product UUID,
	// as set by the board manufacturer and encoded in the BIOS DMI information
	SystemUUID string `protobuf:"bytes,6,opt,name=systemUUID" json:"systemUUID,omitempty"`
	// A random ID that is regenerated on each boot
	BootID string `protobuf:"bytes,7,opt,name=bootID" json:"bootID,omitempty"`
	// Device operating system. One of 386, amd64, arm, s390x, and so on.
	Arch string `protobuf:"bytes,8,opt,name=arch" json:"arch,omitempty"`
	// device operating system. One of darwin, freebsd, linux, windows, and so on
	Os string `protobuf:"bytes,9,opt,name=os" json:"os,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Info) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Info) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Info) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Info) GetGrpcPort() int64 {
	if m != nil {
		return m.GrpcPort
	}
	return 0
}

func (m *Info) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *Info) GetSystemUUID() string {
	if m != nil {
		return m.SystemUUID
	}
	return ""
}

func (m *Info) GetBootID() string {
	if m != nil {
		return m.BootID
	}
	return ""
}

func (m *Info) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Info) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

type Label struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Label) Reset()                    { *m = Label{} }
func (m *Label) String() string            { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()               {}
func (*Label) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Label) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*InfoRequest)(nil), "eliot.services.containers.v1.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "eliot.services.containers.v1.InfoResponse")
	proto.RegisterType((*Info)(nil), "eliot.services.containers.v1.Info")
	proto.RegisterType((*Label)(nil), "eliot.services.containers.v1.Label")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Device service

type DeviceClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type deviceClient struct {
	cc *grpc.ClientConn
}

func NewDeviceClient(cc *grpc.ClientConn) DeviceClient {
	return &deviceClient{cc}
}

func (c *deviceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/eliot.services.containers.v1.Device/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Device service

type DeviceServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterDeviceServer(s *grpc.Server, srv DeviceServer) {
	s.RegisterService(&_Device_serviceDesc, srv)
}

func _Device_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eliot.services.containers.v1.Device/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Device_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eliot.services.containers.v1.Device",
	HandlerType: (*DeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Device_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/device/v1/device.proto",
}

func init() { proto.RegisterFile("services/device/v1/device.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcf, 0x8b, 0xd4, 0x30,
	0x18, 0xa5, 0x3f, 0xa6, 0x6e, 0xbf, 0x51, 0x91, 0x20, 0x12, 0x96, 0x45, 0x4b, 0xbd, 0x54, 0x0f,
	0x0d, 0x3b, 0x82, 0x97, 0xc1, 0x8b, 0x14, 0xa1, 0xe0, 0x41, 0x0a, 0x7b, 0x11, 0x3c, 0xa4, 0x9d,
	0x6f, 0xdb, 0xb2, 0x6d, 0x52, 0x93, 0x4c, 0x61, 0xfe, 0x0e, 0xff, 0x61, 0x69, 0xda, 0x99, 0x11,
	0x84, 0x61, 0x4e, 0xf9, 0xde, 0xcb, 0x7b, 0x0f, 0x92, 0xf7, 0xc1, 0x3b, 0x8d, 0x6a, 0x6c, 0x2b,
	0xd4, 0x6c, 0x87, 0xd3, 0xc9, 0xc6, 0xfb, 0x65, 0x4a, 0x07, 0x25, 0x8d, 0x24, 0x77, 0xd8, 0xb5,
	0xd2, 0xa4, 0x47, 0x59, 0x5a, 0x49, 0x61, 0x78, 0x2b, 0x50, 0xe9, 0x74, 0xbc, 0x8f, 0x5f, 0xc0,
	0x3a, 0x17, 0x8f, 0xb2, 0xc0, 0xdf, 0x7b, 0xd4, 0x26, 0xfe, 0x06, 0xcf, 0x67, 0xa8, 0x07, 0x29,
	0x34, 0x92, 0xcf, 0xe0, 0xb7, 0xe2, 0x51, 0x52, 0x27, 0x72, 0x92, 0xf5, 0x26, 0x4e, 0x2f, 0x65,
	0xa5, 0xd6, 0x69, 0xf5, 0xf1, 0x1f, 0x17, 0xfc, 0x09, 0x92, 0x2d, 0x04, 0x1d, 0x2f, 0xb1, 0xd3,
	0xd4, 0x89, 0xbc, 0x64, 0xbd, 0x79, 0x7f, 0x39, 0xe2, 0xfb, 0xa4, 0x2d, 0x16, 0x0b, 0xb9, 0x85,
	0x9b, 0x46, 0x6a, 0x23, 0x78, 0x8f, 0xd4, 0x8d, 0x9c, 0x24, 0x2c, 0x4e, 0x98, 0xdc, 0x41, 0xc8,
	0x77, 0x3b, 0x85, 0x5a, 0xa3, 0xa6, 0x5e, 0xe4, 0x25, 0x61, 0x71, 0x26, 0x26, 0x67, 0xad, 0x86,
	0xea, 0x87, 0x54, 0x86, 0xfa, 0x91, 0x93, 0x78, 0xc5, 0x09, 0x4f, 0xce, 0x9e, 0x57, 0x4d, 0x2b,
	0x30, 0xcf, 0xe8, 0xca, 0xc6, 0x9e, 0x09, 0xf2, 0x16, 0x40, 0x1f, 0xb4, 0xc1, 0xfe, 0xe1, 0x21,
	0xcf, 0x68, 0x60, 0xaf, 0xff, 0x61, 0xc8, 0x1b, 0x08, 0x4a, 0x29, 0x4d, 0x9e, 0xd1, 0x67, 0xf6,
	0x6e, 0x41, 0x84, 0x80, 0xcf, 0x55, 0xd5, 0xd0, 0x1b, 0xcb, 0xda, 0x99, 0xbc, 0x04, 0x57, 0x6a,
	0x1a, 0x5a, 0xc6, 0x95, 0x3a, 0x66, 0xb0, 0xb2, 0x0f, 0x24, 0xaf, 0xc0, 0x7b, 0xc2, 0x83, 0xfd,
	0xd5, 0xb0, 0x98, 0x46, 0xf2, 0x1a, 0x56, 0x23, 0xef, 0xf6, 0xc7, 0x77, 0xce, 0x60, 0x53, 0x43,
	0x90, 0xd9, 0x2e, 0xc9, 0xaf, 0xe5, 0x3f, 0x3f, 0x5c, 0x51, 0xc1, 0xdc, 0xe5, 0xed, 0xc7, 0x6b,
	0xa4, 0x73, 0xcf, 0x5f, 0xbf, 0xfc, 0xdc, 0xd6, 0xad, 0x69, 0xf6, 0x65, 0x5a, 0xc9, 0x9e, 0xa1,
	0x12, 0x92, 0xf3, 0x81, 0x33, 0x1b, 0xc0, 0x86, 0xa7, 0x9a, 0xf1, 0xa1, 0x65, 0xff, 0x6f, 0xda,
	0x76, 0x9e, 0xca, 0xc0, 0xae, 0xda, 0xa7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xc2, 0x90,
	0x14, 0x8d, 0x02, 0x00, 0x00,
}
